Add Doxygen script for all project
- Update pre-commit to use Doxygen and verify some warnings

Signed-off-by: Uilian Ries <uilianries@gmail.com>

diff --git a/script/pre-commit b/script/pre-commit
--- a/script/pre-commit
+++ b/script/pre-commit
@@ -25,12 +25,17 @@ pattern='\.(c|cpp|cc|cxx|h|hpp)$'
 changed_files=$(git diff-index --cached --name-only $against | grep -E $pattern)
 
 script/format.sh
+script/doxygen.sh
+if [ $? -ne 0 ]; then
+    echo "Could not commit: Rejected by Doxygen"
+    exit 1
+fi
 
 if [ -n "$changed_files" ]; then
     script/linter.sh $changed_files
     if [ $? -ne 0 ]; then
         echo "Could commit: Rejected by linter"
-	exit 1
+	    exit 1
     fi
     script/static-analysis.sh $changed_files
     if [ $? -ne 0 ]; then
